# permissions for end users to edit appversions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appversion-editor-role
rules:
- apiGroups:
  - ops.getais.cloud
  resources:
  - appversions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ops.getais.cloud
  resources:
  - appversions/status
  verbs:
  - get
