# permissions for end users to view appversions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appversion-viewer-role
rules:
- apiGroups:
  - ops.getais.cloud
  resources:
  - appversions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ops.getais.cloud
  resources:
  - appversions/status
  verbs:
  - get
