---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: operator-role
rules:
- apiGroups:
  - ops.getais.cloud
  resources:
  - updates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ops.getais.cloud
  resources:
  - updates/finalizers
  verbs:
  - update
- apiGroups:
  - ops.getais.cloud
  resources:
  - updates/status
  verbs:
  - get
  - patch
  - update
