# permissions for end users to view updates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: update-viewer-role
rules:
- apiGroups:
  - ops.getais.cloud
  resources:
  - updates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ops.getais.cloud
  resources:
  - updates/status
  verbs:
  - get
